prompt:
  system_role: You are a helpful assistant.
  user_prompt: |
    Provide me answer based on the below context.

    If you are unable to answer based on the given context, please say "I don't know".
rag:
  index_name: financial_regulations
  chunk_size: 300
  chunk_overlap: 20
  num_docs: 5
model:
  temperature: 0.7
  max_tokens: 800
